# Generated by Django 4.2.29 on 2026-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(help_text='Skills and areas of expertise')),
                ('motivation', models.TextField(help_text='Why do you want to volunteer with WNETF?')),
                ('availability', models.CharField(blank=True, help_text='e.g. Weekends, Evenings', max_length=200)),
                ('is_diaspora', models.BooleanField(default=False, help_text='Are you based outside Uganda?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
