# Generated by Django 4.2.29 on 2026-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='password',
            field=models.CharField(default='partner123', max_length=128),
        ),
        migrations.AddField(
            model_name='teammember',
            name='password',
            field=models.CharField(default='admin123', max_length=128),
        ),
    ]
