# Generated by Django 4.2.29 on 2026-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/')),
                ('bio', models.TextField(blank=True)),
                ('is_graduate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
