# Generated by Django 4.2.29 on 2026-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=300)),
                ('university_reg_number', models.CharField(max_length=100)),
                ('university_email', models.EmailField(max_length=254)),
                ('student_number', models.CharField(max_length=100)),
                ('grades', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('other_district', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('personal_statement', models.TextField()),
                ('attachment', models.FileField(upload_to='applications/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
